# worker.py
# Contains the background job logic that Cloud Tasks triggers.
# When a ticket comes in, the gateway enqueues a task pointing here.
# Cloud Tasks sends a POST to /worker/process with the ticket details.
# This module runs the full agent pipeline and stores the result in Firestore.

import os
os.environ["ANONYMIZED_TELEMETRY"] = "False"

import json
from dotenv import load_dotenv
from google.cloud import firestore

from agent.pipeline import process_ticket

load_dotenv()

# ── Firestore client ──────────────────────────────────────────────────────────
db = firestore.Client(project=os.getenv("VERTEX_PROJECT_ID", "ticket-resolver-arnab"))

# Collection where we store both job status and completed reports.
# Every ticket gets one document in here.
COLLECTION = "ticket_jobs"


def create_job(task_id: str, ticket_id: str, ticket_text: str):
    """
    Called by the gateway immediately after receiving a POST /ticket request.
    Creates a Firestore document with status='pending' before enqueuing the task.

    This way GET /result/{task_id} can return 'pending' right away
    instead of 'not found', which would confuse the caller.

    Args:
        task_id:     UUID generated by the gateway — primary key for this job
        ticket_id:   Ticket identifier from the caller e.g. "TKT-001"
        ticket_text: Raw problem description
    """
    db.collection(COLLECTION).document(task_id).set({
        "task_id":     task_id,
        "ticket_id":   ticket_id,
        "ticket_text": ticket_text,
        "status":      "pending",   # pending → processing → done / failed
        "report":      None,
        "error":       None,
        "created_at":  firestore.SERVER_TIMESTAMP,
        "completed_at": None,
    })
    print(f"[Worker] Job created: {task_id} for ticket {ticket_id}")


async def run_job(task_id: str, ticket_id: str, ticket_text: str):
    """
    The actual background work. Called when Cloud Tasks fires the HTTP request
    to POST /worker/process.

    Flow:
      1. Update Firestore status to 'processing'
      2. Run the full agent pipeline (30–60 seconds)
      3. Update Firestore status to 'done' with the report
      4. If anything fails, update status to 'failed' with the error

    Args:
        task_id:     Same UUID from create_job — links this execution to the doc
        ticket_id:   Passed through to the agent pipeline
        ticket_text: Passed through to the agent pipeline
    """
    doc_ref = db.collection(COLLECTION).document(task_id)

    # ── Step 1: Mark as processing ────────────────────────────────────────────
    # The caller polling GET /result/{task_id} will now see 'processing'
    # instead of 'pending', giving them visibility into progress.
    doc_ref.update({
        "status": "processing",
    })
    print(f"[Worker] Starting investigation for {ticket_id} (task: {task_id})")

    try:
        # ── Step 2: Run the full agent pipeline ───────────────────────────────
        # process_ticket() is the same function your existing pipeline exposes.
        # It runs triage → investigation → report generation.
        # This is the slow part — 30–60 seconds.
        report = await process_ticket(
            ticket_id=ticket_id,
            ticket_text=ticket_text,
        )

        # ── Step 3: Store completed report ────────────────────────────────────
        doc_ref.update({
            "status":       "done",
            "report":       report,
            "completed_at": firestore.SERVER_TIMESTAMP,
        })
        print(f"[Worker] Completed investigation for {ticket_id}")

    except Exception as e:
        # ── Step 4: Store failure ─────────────────────────────────────────────
        # Don't let a crash leave the job stuck in 'processing' forever.
        # Record the error so the caller can see what went wrong.
        error_msg = str(e)
        doc_ref.update({
            "status": "failed",
            "error":  error_msg,
            "completed_at": firestore.SERVER_TIMESTAMP,
        })
        print(f"[Worker] FAILED investigation for {ticket_id}: {error_msg}")
        raise   # re-raise so Cloud Tasks knows the job failed and can retry
    